name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main
permissions:
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create pull request
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref }}"
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls" \
            -d '{
                  "title": "Auto Merge Changes",
                  "body": "This pull request was automatically created to merge changes into the main branch.",
                  "head": "$BRANCH",
                  "base": "main"
                }'
